# Generated by Django 3.0.5 on 2020-05-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('sender', models.CharField(db_column='from', max_length=100, verbose_name='From')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('date', models.DateField(db_column='Date', verbose_name='Date')),
                ('greeting_id', models.IntegerField(verbose_name='id')),
            ],
            options={
                'verbose_name_plural': 'records',
            },
        ),
    ]
